def ERROR(messages):
    messages.append('Sorry, I did not get that! :(')


def ELEMENT_NAME_NOT_FINDABLE_BY_WORD(messages, element_name):
    messages.append('I am sorry, but you cannot find elements of name "{}" by word'.format(element_name))


def FIND_BY_WORD(messages, element_name, word):
    messages.append('If I am right, you are looking for...\n'
                    'Element: {}\n'
                    'By word: "{}"\n'
                    'Let me check if it is present the database...\n'.format(element_name.upper(), word))


def NOTHING_FOUND(messages):
    messages.append('Nothing has been found, I am sorry!')


def ONE_RESULT_FOUND(messages):
    messages.append('One result has been found!')


def COUNT_RESULTS_FOUND(messages, count):
    messages.append('{} results have been found!'.format(count))


def SELECT_FOR_INFO(messages):
    messages.append('If you want more information, select one!')


def ONLY_COUNT_DISPLAYED(messages, count):
    messages.append('Only {} will be displayed here!'.format(count))


def EMPTY_CONTEXT_LIST(messages):
    messages.append('What are we talking about? No element has been registered yet!')


def SHOW_CURRENT_ACTION_NAME_CONTEXT(messages, action_name):
    messages.append('Currently we are in the context generated by the action:\n'
                    '\n'
                    '{}'.format(action_name))


def CONTEXT_LIST_RESET(messages):
    messages.append('The context has been reset!')


def SHOW_CONTEXT_BUTTONS(messages):
    messages.append('If you want to go back in the context, select where')
