INTENT_VIEW_RELATED_ELEMENT = 'view_rel_el'
INTENT_VIEW_RELATIONS = 'view_all_rel'
INTENT_SELECT_ELEMENT_BY_POSITION = 'select_el_by_pos'
INTENT_FIND_ELEMENT_BY_WORD = 'find_el_by_word'

INTENT_SHOW_CONTEXT = 'show_context'
INTENT_GO_BACK_TO_CONTEXT_POSITION = 'go_back_to_context_pos'

ENTITY_ELEMENT_TYPE = 'el'
ENTITY_BY_ELEMENT_TYPE = 'by'
ENTITY_WORD = 'word'
ENTITY_POSITION = 'pos'

VALUE_POSITION_RESET_CONTEXT = -1
